Boris:
  # segmentation: K:\Dataset\masks
  classification: C:\Users\rafae\Desktop\Git\EIBoris\medical_mnist
  size: [64, 64]
  # num_classes: 3
  Computation:
    Bottom:
      # attention: true
      net_type: resnet50
      use_segmentation: false
    Top:
      min_samples_split: 4
      max_depth: None
  Storage:
    wm_size: 7
Training:
  epochs: 16
  save_file: trained_mnist_224_8_16.boris
  batch_size: 32
